---
- name: "Add nginx repo"
  ansible.builtin.yum_repository:
    baseurl: "http://nginx.org/packages/mainline/rhel/7/$basearch/"
    enabled: true
    gpgcheck: false
    description: "Nginx repo"
    name: "nginx"

- name: "Install Nginx"
  ansible.builtin.yum:
    name: "nginx"
    state: "installed"

- name: "Add Nginx config"
  ansible.builtin.template:
    src: "default.conf.j2"
    dest: "/etc/nginx/conf.d/default.conf"
    mode: "0644"

- name: "Start and enable Nginx"
  ansible.builtin.service:
    name: "nginx"
    enabled: true
    state: "started"
...